### ISSUE TITLE
Faulty image source

### ISSUE THREAD

**Issue by infinity-atom** [nova-ind/desktopNG#3]
When a DocAI window is created, this function is called:

```js
// ui.js:231
function mbw (title, wid, hei, full, min, quit, id, icon = './assets/img/systemIcons/noicon.svg')
```

`"docai"` is passed into the `icon` argument, creating an `<img>` with a source attribute reading `docai`.

### Suggested fix
Remove the last argument from function call.
```diff
// apps.js:285
- const win = tk.mbw('DocAI', '500px', 'auto', true, undefined, undefined, undefined, "docai");
+ const win = tk.mbw('DocAI', '500px', 'auto', true, undefined, undefined, undefined);
```

<hr>
Tested on Chromium Version 127.0.6533.88 (Official Build) Arch Linux (64-bit)

**Comment by novafurry** [comment]
uwu could've just done a pr

**Comment by novafurry** [comment]
Fixing rn

**Comment by infinity-atom** [comment]
> uwu could've just done a pr

too lazy
